# Generated by Django 6.0.1 on 2026-01-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_fill_part_name_make_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('part_code', models.CharField(max_length=100, verbose_name='Код детали')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_parts', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Запчасть на складе',
                'verbose_name_plural': 'Запчасти на складе',
                'ordering': ['-created_at'],
            },
        ),
    ]
